### ISSUE TITLE
[Epic] Initial feature set

### ISSUE THREAD

**Issue by ckotzbauer** [ckotzbauer/simple-tree-component#14]
This component should have several core features and characteristics. The main three characteristics are
- a "Tree-Only-View" where the complete tree is displayed in a container
- a "Tree-Singleselectbox" where the tree is displayed in a dropdown and one node can be selected
- a "Tree-Multiselectbox" where the tree is displayed in a dropdown and multiple nodes can be selected. They will be shown as pillboxes in closed state.

### High-Level-Features

**Tree-Only-View**
* [x] Searchbar for filtering
* [x] CRUD actions for node
  * [x] Create
  * [x] Update (Rename)
  * [x] Delete
* [x] Reorder nodes on same level (without DnD)
* [x] Collapsing of nodes
* [x] Checkbox selection
  * [x] Customizable checkbox ui
  * [x] Parent check changes selection-state of all childs accordingly
  * [x] Parent check leaves selection-state of childs untouched
* [x] Read-only mode
* [x] Styling

**Tree-Singleselectbox**
* [x] Searchbar for filtering in dropdown
* [x] Collapsing of nodes
* [x] Customizable display of selected node in input field
* [x] Dropdown position (above, below) according to window position
* [x] Customizable icon/area in dropdown on right side
* [x] Dropdown-Arrows (chevrons) with pure CSS
* [x] Read-only mode
* [x] Styling

**Tree-Multiselectbox**
* [x] Searchbar for filtering in dropdown
* [x] Collapsing of nodes
* [x] Pillbox display of selected nodes
  * [x] Customizable text of selected node for each pillbox
* [x] Dropdown position (above, below) according to window position
* [x] Dropdown-Arrows (chevrons) with pure CSS
* [x] Read-only mode
* [x] Styling

### Internal and API features

* [x] Data-layer separated from UI display
* [x] Logic for correct positioning of dropdown flyout could maybe be generic and be exposed
* [x] Validation logic for options (e.g. treeNode-list)
* [x] Expose needed api-methods
* [x] EventHandling logic for internal and external events

### Unit-Tests

* [x] `DataService`
* [x] Node selection
 

### Refactorings

* [x] Share duplicate code beween `Singleselectbox` and `Multiselectbox`
* [x] Make node selection more uniform accross views and make data state leading for display in UI
* [x] Use a UID instead of value to identify nodes to prevent errors with css selectors
